[package]
name = "vpnhide_checks"
version = "1.12.1"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[lib]
name = "vpnhide_checks"
crate-type = ["cdylib", "rlib"]

[dependencies]
uniffi = "0.29"
libc = "0.2"

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 16
panic = "abort"
# Strip manually after build to avoid linker issues with -nodefaultlibs

[profile.dev]
panic = "abort"
