Run softprops/action-gh-release@v2
  with:
    files: dist/libvpnhide_checks.so/libvpnhide_checks.so
  dist/vpnhide-kmod-*/vpnhide-kmod-*.zip
  
    draft: false
    generate_release_notes: true
    overwrite_files: true
    token: ***
  env:
    GITHUB_TOKEN: ***
Error: ⚠️ GitHub Releases requires a tag